export const bases = [
  {
    name: 'Лобня',
    address: {
        country: 'Россия',
        addressLevel1: 'Московская область',
        addressLevel2: '',
        addressLevel3: 'Лобня',
        addressLevel4: '',
        streetLevel1: 'Краснополянский',
        streetLevel2: 'д. 6',
        streetType: 'тупик',
    },
    coords: {
      lat: 56.028078,
      lng: 37.448096,
    },
  },
  {
    name: 'Электроугли',
    address: {
        country: 'Россия',
        addressLevel1: 'Московская область',
        addressLevel2: '',
        addressLevel3: 'Электроугли',
        addressLevel4: '',
        streetLevel1: 'Полевая',
        streetLevel2: '1А',
        streetType: 'ул.',
    },
    coords: {
      lat: 55.725640,
      lng: 38.214017,
    },
  },
  {
    name: 'Чехов',
    address: {
        country: 'Россия',
        addressLevel1: 'Московская область',
        addressLevel2: 'Чеховский район',
        addressLevel3: '',
        addressLevel4: 'п. Столбовая',
        streetLevel1: 'Заводская',
        streetLevel2: '1',
        streetType: 'ул.',
    },
    coords: {
      lat: 55.2484763,
      lng: 37.4903875,
    },
  },
  {
    name: 'Белгород',
    address: {
        country: 'Россия',
        addressLevel1: 'Белгородская область',
        addressLevel2: '',
        addressLevel3: 'Белгород',
        addressLevel4: '',
        streetLevel1: 'Почтовый 4-ый',
        streetLevel2: 'д. 16',
        streetType: 'пер.',
    },
    coords: {
      lat: 50.585865,
      lng: 36.669562,
    },
  },
  {
    name: 'Брянск',
    address: {
        country: 'Россия',
        addressLevel1: 'Брянская область',
        addressLevel2: '',
        addressLevel3: 'Брянск',
        addressLevel4: 'пгт. Большое Полпино,',
        streetLevel1: 'Октябрьский',
        streetLevel2: 'д. 2',
        streetType: 'пер.',
    },
    coords: {
      lat: 53.246165,
      lng: 34.493744,
    },
  },
  {
    name: 'Владикавказ',
    address: {
        country: 'Россия',
        addressLevel1: 'Республика Северная Осетия-Алания',
        addressLevel2: '',
        addressLevel3: 'Владикавказ',
        addressLevel4: '',
        streetLevel1: '6-я Промышленная',
        streetLevel2: 'д. 3',
        streetType: 'ул.',
    },
    coords: {
      lat: 43.075249,
      lng: 44.690986,
    },
  },
  {
    name: 'Владимир',
    address: {
        country: 'Россия',
        addressLevel1: 'Владимирская область',
        addressLevel2: '',
        addressLevel3: 'Владимир',
        addressLevel4: '',
        streetLevel1: 'Складская',
        streetLevel2: 'д. 2',
        streetType: 'ул.',
    },
    coords: {
      lat: 56.095685,
      lng: 40.345594,
    },
  },
  {
    name: 'Волгоград',
    address: {
        country: 'Россия',
        addressLevel1: 'Волгоградская область',
        addressLevel2: '',
        addressLevel3: 'Волгоград',
        addressLevel4: '',
        streetLevel1: 'Шопена',
        streetLevel2: 'д. 4в',
        streetType: 'ул.',
    },
    coords: {
      lat: 48.779071,
      lng: 44.476135,
    },
  },
  {
    name: 'Вологда',
    address: {
        country: 'Россия',
        addressLevel1: 'Вологодская область',
        addressLevel2: '',
        addressLevel3: 'Вологда',
        addressLevel4: '',
        streetLevel1: 'Клубова',
        streetLevel2: 'д. 29а',
        streetType: 'ул.',
    },
    coords: {
      lat: 59.236796,
      lng: 39.808245,
    },
  },
  {
    name: 'Воронеж',
    address: {
        country: 'Россия',
        addressLevel1: 'Воронежская область',
        addressLevel2: '',
        addressLevel3: 'Воронеж',
        addressLevel4: '',
        streetLevel1: 'Ильюшина',
        streetLevel2: 'д. 12',
        streetType: 'ул.',
    },
    coords: {
      lat: 51.642036,
      lng: 39.290556,
    },
  },
  {
    name: 'Екатеринбург',
    address: {
        country: 'Россия',
        addressLevel1: 'Свердловская область',
        addressLevel2: '',
        addressLevel3: 'Екатеринбург',
        addressLevel4: 'п.Большой Исток',
        streetLevel1: 'Свердлова',
        streetLevel2: 'д. 42',
        streetType: 'ул.',
    },
    coords: {
      lat: 56.725783,
      lng: 60.755990,
    },
  },
  {
    name: 'Ижевск',
    address: {
        country: 'Россия',
        addressLevel1: 'Удмуртская Республика',
        addressLevel2: '',
        addressLevel3: 'Екатеринбург',
        addressLevel4: '',
        streetLevel1: 'Маркина',
        streetLevel2: 'д. 195',
        streetType: 'ул.',
    },
    coords: {
      lat: 56.827069,
      lng: 53.274902,
    },
  },
  {
    name: 'Казань',
    address: {
        country: 'Россия',
        addressLevel1: 'Республика Татарстан',
        addressLevel2: 'Высокогорский район',
        addressLevel3: '',
        addressLevel4: 'село Высокая Гора',
        streetLevel1: 'Луговая',
        streetLevel2: 'д. 9',
        streetType: 'ул.',
    },
    coords: {
      lat: 55.906199,
      lng: 49.294548,
    },
  },
  {
    name: 'Калуга',
    address: {
        country: 'Россия',
        addressLevel1: 'Калужская область',
        addressLevel2: '',
        addressLevel3: 'Калуга',
        addressLevel4: '',
        streetLevel1: 'Прончищева',
        streetLevel2: 'д. 25',
        streetType: 'ул.',
    },
    coords: {
      lat: 54.562805,
      lng: 36.328031,
    },
  },
  {
    name: 'Киров',
    address: {
        country: 'Россия',
        addressLevel1: 'Кировская область',
        addressLevel2: '',
        addressLevel3: 'Киров',
        addressLevel4: '',
        streetLevel1: 'Промышленный',
        streetLevel2: 'д. 9',
        streetType: 'пер.',
    },
    coords: {
      lat: 58.619930,
      lng: 49.586968,
    },
  },
  {
    name: 'Краснодар',
    address: {
        country: 'Россия',
        addressLevel1: 'Краснодарский край',
        addressLevel2: 'Динской район',
        addressLevel3: '',
        addressLevel4: 'Станица Новотитаровская',
        streetLevel1: 'Крайняя',
        streetLevel2: 'д. 2/12',
        streetType: 'ул.',
    },
    coords: {
      lat: 45.257803,
      lng: 39.010993,
    },
  },
  {
    name: 'Курск',
    address: {
        country: 'Россия',
        addressLevel1: 'Курская область',
        addressLevel2: '',
        addressLevel3: 'Курск',
        addressLevel4: '',
        streetLevel1: 'Магистральный',
        streetLevel2: 'д. 24В',
        streetType: 'проезд',
    },
    coords: {
      lat: 51.656261,
      lng: 36.152950,
    },
  },
  {
    name: 'Липецк',
    address: {
        country: 'Россия',
        addressLevel1: 'Липецкая область',
        addressLevel2: '',
        addressLevel3: '',
        addressLevel4: 'село Подгорное',
        streetLevel1: 'Лоскутная',
        streetLevel2: 'д. 4',
        streetType: 'ул.',
    },
    coords: {
      lat: 52.549967,
      lng: 39.492014,
    },
  },
  {
    name: 'Махачкала',
    address: {
        country: 'Россия',
        addressLevel1: 'Республика Дагестан',
        addressLevel2: '',
        addressLevel3: 'Каспийск',
        addressLevel4: 'Кирпичный поселок',
        streetLevel1: 'район нефтебазы',
        streetLevel2: '',
        streetType: '',
    },
    coords: {
      lat: 42.887200,
      lng: 47.582705,
    },
  },
  {
    name: 'Набережные Челны',
    address: {
        country: 'Россия',
        addressLevel1: 'Республика Татарстан',
        addressLevel2: '',
        addressLevel3: 'Набережные Челны',
        addressLevel4: '',
        streetLevel1: 'Линейный',
        streetLevel2: 'д. 24',
        streetType: 'проезд',
    },
    coords: {
      lat: 55.680204,
      lng: 52.458807,
    },
  },
  {
    name: 'Нальчик',
    address: {
        country: 'Россия',
        addressLevel1: 'Кабардино-Балкарская Республика',
        addressLevel2: '',
        addressLevel3: 'Нальчик',
        addressLevel4: '',
        streetLevel1: '1-й Промышленный',
        streetLevel2: 'д. 18',
        streetType: 'проезд',
    },
    coords: {
      lat: 43.509200,
      lng: 43.663167,
    },
  },
  {
    name: 'Нижний Новгород',
    address: {
        country: 'Россия',
        addressLevel1: 'Нижегородская область',
        addressLevel2: '',
        addressLevel3: 'Нижний Новгород',
        addressLevel4: '',
        streetLevel1: 'Окская Гавань',
        streetLevel2: 'д. 5А',
        streetType: 'ул.',
    },
    coords: {
      lat: 56.234920,
      lng: 43.910684,
    },
  },
  {
    name: 'Новосибирск',
    address: {
        country: 'Россия',
        addressLevel1: 'Новосибирская область',
        addressLevel2: '',
        addressLevel3: 'Новосибирск',
        addressLevel4: '',
        streetLevel1: 'Клубная',
        streetLevel2: 'д. 45',
        streetType: 'ул.',
    },
    coords: {
      lat: 55.022593,
      lng: 82.786527,
    },
  },
  {
    name: 'Новочеркасск',
    address: {
        country: 'Россия',
        addressLevel1: 'Ростовская область',
        addressLevel2: '',
        addressLevel3: 'Новочеркасск',
        addressLevel4: '',
        streetLevel1: 'Флерова',
        streetLevel2: 'д. 32Б',
        streetType: 'ул.',
    },
    coords: {
      lat: 47.465128,
      lng: 40.084040,
    },
  },
  {
    name: 'Орел',
    address: {
        country: 'Россия',
        addressLevel1: 'Орловская область',
        addressLevel2: '',
        addressLevel3: 'Орел',
        addressLevel4: '',
        streetLevel1: 'Северный парк',
        streetLevel2: 'д. 1',
        streetType: 'ул.',
    },
    coords: {
      lat: 53.013269,
      lng: 36.104150,
    },
  },
  {
    name: 'Оренбург',
    address: {
        country: 'Россия',
        addressLevel1: 'Оренбургская область',
        addressLevel2: '',
        addressLevel3: 'Оренбург',
        addressLevel4: '',
        streetLevel1: 'Беляевская',
        streetLevel2: 'д. 18/4',
        streetType: 'ул.',
    },
    coords: {
      lat: 51.725842,
      lng: 55.115760,
    },
  },
  {
    name: 'Пенза',
    address: {
        country: 'Россия',
        addressLevel1: 'Пензенская область',
        addressLevel2: '',
        addressLevel3: 'Пенза',
        addressLevel4: '',
        streetLevel1: 'Байдукова',
        streetLevel2: 'д. 100',
        streetType: 'ул.',
    },
    coords: {
      lat: 53.237660,
      lng: 44.998497,
    },
  },
  {
    name: 'Пермь',
    address: {
        country: 'Россия',
        addressLevel1: 'Пермский край',
        addressLevel2: '',
        addressLevel3: 'Пермь',
        addressLevel4: '',
        streetLevel1: 'Верхне-Муллинская',
        streetLevel2: 'д. 132А',
        streetType: 'ул.',
    },
    coords: {
      lat: 53.237660,
      lng: 44.998497,
    },
  },
  {
    name: 'Пятигорск',
    address: {
        country: 'Россия',
        addressLevel1: 'Ставропольский край',
        addressLevel2: '',
        addressLevel3: 'Пятигорск',
        addressLevel4: '',
        streetLevel1: 'Черкесское',
        streetLevel2: 'д. 37 А',
        streetType: 'шоссе',
    },
    coords: {
      lat: 44.059071,
      lng: 42.983740,
    },
  },
  {
    name: 'Ростов-на-Дону',
    address: {
        country: 'Россия',
        addressLevel1: 'Ростовская область',
        addressLevel2: '',
        addressLevel3: 'Ростов-на-Дону',
        addressLevel4: '',
        streetLevel1: 'Доватора',
        streetLevel2: 'д. 148Ж',
        streetType: 'ул.',
    },
    coords: {
      lat: 47.247642,
      lng: 39.601206,
    },
  },
  {
    name: 'Рязань',
    address: {
        country: 'Россия',
        addressLevel1: 'Рязанская область',
        addressLevel2: '',
        addressLevel3: 'Рязань',
        addressLevel4: '',
        streetLevel1: 'Прижелезнодорожная',
        streetLevel2: 'д. 6',
        streetType: 'ул.',
    },
    coords: {
      lat: 54.670321,
      lng: 39.620537,
    },
  },
  {
    name: 'Самара',
    address: {
        country: 'Россия',
        addressLevel1: 'Самарская область',
        addressLevel2: '',
        addressLevel3: 'Самара',
        addressLevel4: 'пос. Зубчаниновка',
        streetLevel1: 'Зубчаниновское',
        streetLevel2: 'д. 130А',
        streetType: 'шоссе',
    },
    coords: {
      lat: 53.228606,
      lng: 50.286171,
    },
  },
  {
    name: 'Санкт-Петербург',
    address: {
        country: 'Россия',
        addressLevel1: 'Ленинградская область',
        addressLevel2: 'Тосненский район',
        addressLevel3: '',
        addressLevel4: 'пос. Форносово',
        streetLevel1: 'Павловское',
        streetLevel2: 'д. 32',
        streetType: 'шоссе',
    },
    coords: {
      lat: 59.574834,
      lng: 30.546439,
    },
  },
  {
    name: 'Саранск',
    address: {
        country: 'Россия',
        addressLevel1: 'Республика Мордовия',
        addressLevel2: '',
        addressLevel3: 'Саранск',
        addressLevel4: '',
        streetLevel1: 'Александровское',
        streetLevel2: '39',
        streetType: 'шоссе',
    },
    coords: {
      lat: 54.228882,
      lng: 45.220657,
    },
  },
  {
    name: 'Саратов',
    address: {
        country: 'Россия',
        addressLevel1: 'Саратовская область',
        addressLevel2: 'Саратовский район,',
        addressLevel3: '',
        addressLevel4: 'промузел Зоринский',
        streetLevel1: 'АО «Металлоторг»',
        streetLevel2: 'стр. 1',
        streetType: 'промузел',
    },
    coords: {
      lat: 51.639775,
      lng: 46.014826,
    },
  },
  {
    name: 'Ставрополь',
    address: {
        country: 'Россия',
        addressLevel1: 'Ставропольский край',
        addressLevel2: '',
        addressLevel3: 'Михайловск',
        addressLevel4: 'с. Верхнерусское',
        streetLevel1: 'Восточный',
        streetLevel2: 'д. 8',
        streetType: 'проезд',
    },
    coords: {
      lat: 45.126066,
      lng: 41.970358,
    },
  },
  {
    name: 'Старый Оскол',
    address: {
        country: 'Россия',
        addressLevel1: 'Белгородская область',
        addressLevel2: '',
        addressLevel3: 'Старый Оскол',
        addressLevel4: 'Станция Котёл',
        streetLevel1: 'площадка Монтажная, М-4',
        streetLevel2: 'д. 22, стр.1',
        streetType: 'проезд',
    },
    coords: {
      lat: 51.227276,
      lng: 37.911492,
    },
  },
  {
    name: 'Сызрань',
    address: {
        country: 'Россия',
        addressLevel1: 'Самарская область',
        addressLevel2: '',
        addressLevel3: 'Сызрань',
        addressLevel4: '',
        streetLevel1: 'Промышленная',
        streetLevel2: 'д. 12',
        streetType: 'ул.',
    },
    coords: {
      lat: 53.073071,
      lng: 48.412842,
    },
  },
  {
    name: 'Сызрань',
    address: {
        country: 'Россия',
        addressLevel1: 'Самарская область',
        addressLevel2: '',
        addressLevel3: 'Сызрань',
        addressLevel4: '',
        streetLevel1: 'Промышленная',
        streetLevel2: 'д. 12',
        streetType: 'ул.',
    },
    coords: {
      lat: 53.073071,
      lng: 48.412842,
    },
  },
  {
    name: 'Тверь',
    address: {
        country: 'Россия',
        addressLevel1: 'Тверская область',
        addressLevel2: '',
        addressLevel3: 'Тверь',
        addressLevel4: '',
        streetLevel1: 'Бочкина',
        streetLevel2: 'д. 13',
        streetType: 'ул.',
    },
    coords: {
      lat: 56.804328,
      lng: 35.982575,
    },
  },
  {
    name: 'Тула',
    address: {
        country: 'Россия',
        addressLevel1: 'Тульская область',
        addressLevel2: '',
        addressLevel3: 'Тула',
        addressLevel4: 'пос. Плеханово',
        streetLevel1: 'Ленина',
        streetLevel2: 'д. 1А',
        streetType: 'ул.',
    },
    coords: {
      lat: 54.233985,
      lng: 37.548860,
    },
  },
  {
    name: 'Тюмень',
    address: {
        country: 'Россия',
        addressLevel1: 'Тюменская область',
        addressLevel2: '',
        addressLevel3: 'Тюмень',
        addressLevel4: '',
        streetLevel1: 'Производственная',
        streetLevel2: 'д. 25С2',
        streetType: 'ул.',
    },
    coords: {
      lat: 57.150880,
      lng: 65.374293,
    },
  },
  {
    name: 'Ульяновск',
    address: {
        country: 'Россия',
        addressLevel1: 'Ульяновская область',
        addressLevel2: '',
        addressLevel3: 'Ульяновск',
        addressLevel4: '',
        streetLevel1: 'Доватора',
        streetLevel2: 'д. 1',
        streetType: 'ул.',
    },
    coords: {
      lat: 54.297754,
      lng: 48.305287,
    },
  },
  {
    name: 'Уфа',
    address: {
        country: 'Россия',
        addressLevel1: 'Республика Башкортостан',
        addressLevel2: '',
        addressLevel3: 'Уфа',
        addressLevel4: '',
        streetLevel1: 'Глазовская',
        streetLevel2: 'д. 26/2',
        streetType: 'ул.',
    },
    coords: {
      lat: 54.693119,
      lng: 55.843626,
    },
  },
  {
    name: 'Чебоксары',
    address: {
        country: 'Россия',
        addressLevel1: 'Чувашская Республика',
        addressLevel2: '',
        addressLevel3: 'Чебоксары',
        addressLevel4: '',
        streetLevel1: 'Лапсарский',
        streetLevel2: 'д. 27',
        streetType: 'проезд',
    },
    coords: {
      lat: 56.065997,
      lng: 47.247359,
    },
  },
  {
    name: 'Челябинск',
    address: {
        country: 'Россия',
        addressLevel1: 'Челябинская область',
        addressLevel2: '',
        addressLevel3: 'Челябинск',
        addressLevel4: '',
        streetLevel1: 'Троицкий тракт',
        streetLevel2: 'д. 35',
        streetType: 'ул.',
    },
    coords: {
      lat: 55.098042,
      lng: 61.386968,
    },
  },
  {
    name: 'Череповец',
    address: {
        country: 'Россия',
        addressLevel1: 'Вологодская область',
        addressLevel2: '',
        addressLevel3: 'Череповец',
        addressLevel4: '',
        streetLevel1: 'Осенняя',
        streetLevel2: 'д. 11Б',
        streetType: 'ул.',
    },
    coords: {
      lat: 59.149928,
      lng: 37.909883,
    },
  },
  {
    name: 'Ярославль',
    address: {
        country: 'Россия',
        addressLevel1: 'Ярославская область',
        addressLevel2: '',
        addressLevel3: 'Ярославль',
        addressLevel4: '',
        streetLevel1: 'Гагарина',
        streetLevel2: 'д. 75',
        streetType: 'ул.',
    },
    coords: {
      lat: 57.569238,
      lng: 39.809192,
    },
  },

];
